### ISSUE TITLE
Show History

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#2]
It'd be cool to see a list of all the searches. Maybe even make them clickable. History does not persist beyond browser session.

![screenshot](https://dl.dropbox.com/s/wf5u8f0h3ui0wqe/Screenshot%202020-05-25%2009.43.50.png?dl=0)

**Comment by icegotcha** [comment]
Can I try it?

**Comment by gregrickaby** [comment]
@icegotcha Yes! You're welcome to tackle any issue you'd like 😄

**Comment by icegotcha** [comment]
OK. Thank you! 😁

**Comment by icegotcha** [comment]
Hello,
I sent a PR. Please see at #84
(Sorry for the late delivery. 😅 )
