### ISSUE TITLE
Support HLS Video

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#391]
In addition to `.MP4`, Reddit also returns HLS-based video playlists in the API response. HLS is supported by all major browsers and has advantages, such as optimized video delivery for mobile devices. 

The motivation for this is that the `.MP4s` returned by the Reddit API do not have sound, but the HLS versions do.

- [ ] Create an `<HlsPlayer />` component leveraging [hls.js](https://github.com/video-dev/hls.js/blob/master/demo/basic-usage.html)
- [ ] The component must support `<video>` fallbacks with the `MP4` URL
- [ ] Replace the `<video>` tag in the `<Card />` component with `<HlsPlayer />`

**Comment by rudychung** [comment]
Hi! I'd like to give this a try, could you assign me to this?

**Comment by gregrickaby** [comment]
Sounds good. Please review the contribution guidelines. 👍🏻
