### ISSUE TITLE
Logo link and other functionality

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#394]
When a user clicks the "Reddit Image Viewer" text in the header, it should clear the search, which will load the default sub `itookapicture`.

- [ ] Create clear function
- [ ] Hook up to header "logo" text

**Comment by AloyBranCheung** [comment]
Hi @gregrickaby, i'd like to give this a shot for hacktoberfest if that's alright.

**Comment by gregrickaby** [comment]
@AloyBranCheung Awesome! Have at it!
