### ISSUE TITLE
Videos - Link to original post

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#409]
Currently you can click an image to view the original post on Reddit. For other media like videos, you cannot, because clicking it plays the video.

- [ ] Either above or below each video, add the Post Title
- [ ] The Post Title should back to the original post on Reddit
- [ ] Nice to have: Show the Post Title underneath images too

**Comment by Shansince2k3** [comment]
@gregrickaby  I would like to work on this

**Comment by gregrickaby** [comment]
@Shansince2k3 Sounds good. Please review the Contributing guidelines.

**Comment by Shansince2k3** [comment]
@gregrickaby  The local hosting process kind a complicated for me. Sorry I guess I could not do that

**Comment by rudychung** [comment]
Hi, I'd like to take this one on. Could you assign me?

**Comment by gregrickaby** [comment]
@rudychung Sure thing!
