### ISSUE TITLE
Add popular subreddits to search drawer on initial focus

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#410]
When a user clicks/taps the search bar the drop down reads, "nothing found try searching". 

Instead, it should show the the Top 5 (or 10) popular Subreddits. See Mantine's [Autocomplete](https://mantine.dev/core/autocomplete/) docs.

- [ ] When a user clicks/taps into search bar, display 5 or 10 Popular Subreddits
- [ ] Follow the [API docs](https://www.reddit.com/dev/api#GET_subreddits_popular) for the query 
- [ ] The subreddits listed in the drodpown should match the style and display `NSFW` badge if necessary

**Comment by sfrunza13** [comment]
Can I try to work on this?
