### ISSUE TITLE
Break up into components

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#59]
Right now, this is a simple SPA with everything contained in `/pages/index.js`.

Really, I need a `<Layout />`, and `<Header />` components, so we can easily create other pages.

**Comment by saraogipraveen** [comment]
hi @gregrickaby, would like to take this up. Please assign

**Comment by syauqy** [comment]
Hi @gregrickaby , what a nice project. Could you assign this to me?
Sorry, let me clarify what you mean.
So do you want to put only `<Layout />` component inside the index.js? And then put `<Sitehead />` and the rest inside the layout?

**Comment by gregrickaby** [comment]
Exactly!

Then I can create other pages and update the 404 page to match sitewide layout.

**Comment by syauqy** [comment]
Hi @gregrickaby  Please kindly check this #70 PR.
But I think I broke the changes by accidentally click merge 'main' to my branch.
I want to make sure if it's still okay.
