### ISSUE TITLE
Better infinite scroll

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#60]
On the initial page load, we're grabbing 200 items from Reddit. This request can take up 10 seconds to resolve.

Is there a way to grab the first 5 items, and then continue to make requests as the user scrolls?

**Comment by icegotcha** [comment]
I would like to try it. Please assign to me

**Comment by icegotcha** [comment]
Hello, @gregrickaby 
I sent a PR. Please check at #75.

**Comment by gregrickaby** [comment]
Closed with https://github.com/gregrickaby/reddit-image-viewer/pull/75
