### ISSUE TITLE
Allow multi-subreddits in search

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/reddit-image-viewer#62]
It would be cool if a user could use `itookapicture+pics+aww` in the search to pull in all of those subreddits and their respective media.

**Comment by agarwalamn** [comment]
Can be done by adding a +(Add) button at the search bar and will search multiple queries

**Comment by gregrickaby** [comment]
Right, then pass it along to the `useEffect()` hook where the query happens.

**Comment by agarwalamn** [comment]
I am not that great with NEXT.JS but can I try?
